export const QUANTITY_UNIT_OPTIONS = Object.freeze([
  { value: 'Nos', label: 'Numbers (Nos)' },
  { value: 'Piece', label: 'Piece (pc)' },
  { value: 'Unit', label: 'Unit' },
  { value: 'Set', label: 'Set' },
  { value: 'Pair', label: 'Pair' },
  { value: 'Dozen', label: 'Dozen' },
  { value: 'Pack', label: 'Pack' },
  { value: 'Packet', label: 'Packet' },
  { value: 'Box', label: 'Box' },
  { value: 'Carton', label: 'Carton' },
  { value: 'Bundle', label: 'Bundle' },
  { value: 'Bag', label: 'Bag' },
  { value: 'Bottle', label: 'Bottle' },
  { value: 'Can', label: 'Can' },
  { value: 'Jar', label: 'Jar' },
  { value: 'Milligram', label: 'Milligram (mg)' },
  { value: 'Gram', label: 'Gram (g)' },
  { value: 'Kg', label: 'Kilogram (kg)' },
  { value: 'Quintal', label: 'Quintal' },
  { value: 'Ton', label: 'Metric ton' },
  { value: 'ML', label: 'Millilitre (ml)' },
  { value: 'Litre', label: 'Litre (L)' },
  { value: 'MM', label: 'Millimeter (mm)' },
  { value: 'CM', label: 'Centimeter (cm)' },
  { value: 'Meter', label: 'Meter (m)' },
  { value: 'Kilometer', label: 'Kilometer (km)' },
  { value: 'Inch', label: 'Inch (in)' },
  { value: 'Foot', label: 'Foot (ft)' },
  { value: 'Yard', label: 'Yard (yd)' },
  { value: 'Sq Ft', label: 'Square foot (sq ft)' },
  { value: 'Sq M', label: 'Square meter (sq m)' },
  { value: 'Acre', label: 'Acre' },
  { value: 'Hectare', label: 'Hectare' },
  { value: 'Cubic Ft', label: 'Cubic foot (cu ft)' },
  { value: 'Cubic M', label: 'Cubic meter (cu m)' },
  { value: 'Roll', label: 'Roll' },
  { value: 'Sheet', label: 'Sheet' },
  { value: 'Tray', label: 'Tray' },
  { value: 'Coil', label: 'Coil' },
  { value: 'Hour', label: 'Hour' },
  { value: 'Day', label: 'Day' },
  { value: 'Week', label: 'Week' },
  { value: 'Month', label: 'Month' },
  { value: 'Year', label: 'Year' },
  { value: 'Job/Service', label: 'Job / Service' },
]);

export const formatQuantityWithUnit = (quantity, unit) =>
  [quantity, unit]
    .map((value) => String(value ?? '').trim())
    .filter(Boolean)
    .join(' ');
